const datos = [
    {
        imagen: "../../src/img/user2.jpg",
        usuario: "Soyfranpe1",
        post: "https://www.youtube.com/embed/jxp3SngYb4w",
        visualizaciones: "9.652 Reproducciones",
        texto: "Saludos Para Mi Empresa Ceramica Chero 2022 Jajaja",
        hashtags: {
            uno: "#omegle",
            dos: "#risas",
            tres: "#Fb",
            cuatro: "#ig",
        },
        comentarios: "Ver Los 30 Comentarios",
        fecha: "16 DE ABRIL",
        id: 1,
    },
    {
        imagen: "../../src/img/user3.jpg",
        usuario: "mateo",
        post: "https://www.intentarlo.com/wp-content/uploads/2018/01/frases-para-estados-de-instagram.jpg",
        visualizaciones: "1.652 vistas",
        texto: "Vive la vida al maximo ",
        hashtags: {
            uno: "#vive",
            dos: "#post",
            tres: "#corazones",
            cuatro: "#ig",
        },
        comentarios: "Ver los 100 comentarios",
        fecha: "22 DE ABRIL",
        id: 2,
    },
    {
        imagen: "../../src/img/user4.jpg",
        usuario: "James",
        post: "https://billboard.com.ar/wp-content/uploads/2021/02/alan_walker_salem_ilese_fake_a_smile_composite.jpg",
        visualizaciones: "55.652 vistas",
        texto: " Musica para tu vida con Alan Walker.",
        hashtags: {
            uno: "#vive",
            dos: "#post",
            tres: "#alanWalker",
            cuatro: "#ig",
        },
        comentarios: "Ver los 25500 comentarios",
        fecha: "30 DE MAYO",
        id: 3,
    },
    {
        imagen: "../../src/img/user5.jpg",
        usuario: "sebastian",
        post: "https://i.ytimg.com/vi/Sp6zkZY8V5s/sddefault.jpg",
        visualizaciones: "35.652 vistas",
        texto: "Alan Walker Style - Space (New Song 2021)",
        hashtags: {
            uno: "#Song",
            dos: "#post",
            tres: "#alanWalker",
            cuatro: "#ig",
        },
        comentarios: "Ver los 1500 comentario",
        fecha: "10 DE MAYO",
        id: 4,
    },
    {
        imagen: "../../src/img/user6.jpg",
        usuario: "Ldinz",
        post: "https://televisa.brightspotcdn.com/dims4/default/288022d/2147483647/strip/true/crop/1200x675+0+44/resize/1200x675!/quality/90/?url=https%3A%2F%2Ftelevisa-brightspot.s3.amazonaws.com%2Fapi%2Fff%2Fe8%2F0f5badd2499a91dc6502d7b280ed%2Folivia-rodrigo-woman-of-the-year-de-billboard.jpg",
        visualizaciones: "5.652 vistas",
        texto: "Olivia Rodrigo es nombrada Mujer del Año por Billboard en 2022 | Música | Telehit",
        hashtags: {
            uno: "#Song",
            dos: "#Ldinz",
            tres: "#Billboard",
            cuatro: "#Olivia",
        },
        comentarios: "Ver los 6500 comentarios",
        fecha: "15 DE ENERO",
        id: 5,
    },
    {
        imagen: "../../src/img/user7.jpg",
        usuario: "axel",
        post: "https://d3u63wyfuci0ch.cloudfront.net/wp-content/uploads/2020/12/17115717/spider-man-3-spiderverse.jpg",
        visualizaciones: "1.652 vistas",
        texto: "Andrew Garfield y Tobey Maguire acompañarían a Tom Holland en Spider-Man 3",
        hashtags: {
            uno: "#Andrew",
            dos: "#Garfield",
            tres: "#Tobey",
            cuatro: "#Holland",
        },
        comentarios: "Ver los 1300 comentarios",
        fecha: "12 DE ABRIL",
        id: 6,
    },
    {
        imagen: "../../src/img/user14.jpg",
        usuario: "elcanita7w7",
        post: "https://www.youtube.com/embed/71ErnglDYG8",
        visualizaciones: "6.652 vistas",
        texto: "LOGRO ENAMORAR A UNA ESPAÑOLA EN OMEGLE!!",
        hashtags: {
            uno: "#omegle",
            dos: "#Fb",
            tres: "#Cañita",
            cuatro: "#ig",
        },
        comentarios: "Ver los 3100 comentarios",
        fecha: "20 DE ABRIL",
        id: 7,
    },
    {
        imagen: "../../src/img/user8.jpg",
        usuario: "Daylentriplea",
        post: "https://www.youtube.com/embed/ebzYOhtJwfA",
        visualizaciones: "6.652 vistas",
        texto: "NDYNZEIN BUSCANDO NOVIA PARA ELCAÑITA (Bailes Prohibidos)",
        hashtags: {
            uno: "#ELCAÑITA",
            dos: "#Fb",
            tres: "#NDYNZEIN",
            cuatro: "#ig",
        },
        comentarios: "Ver los 2100 comentarios",
        fecha: "28 DE ABRIL",
        id: 8,
    },
    {
        imagen: "../../src/img/user9.jpg",
        usuario: "Andy",
        post: "https://www.literato.es/images/cf/cfb32d81a6e0e9f83ba03342af2d2149.jpg",
        visualizaciones: "2.652 vistas",
        texto: "Jean-Jacques Rousseau: El amor propio hace más liber",
        hashtags: {
            uno: "#Jean",
            dos: "#Fb",
            tres: "#amor",
            cuatro: "#ig",
        },
        comentarios: "Ver los 1200 comentarios",
        fecha: "18 DE ABRIL",
        id: 9,
    },
    {
        imagen: "../../src/img/user10.jpg",
        usuario: "Yatra",
        post: "https://pbs.twimg.com/media/BwUx0-VIQAA_kNJ.jpg",
        visualizaciones: "2.652 vistas",
        texto: "Frases 3MSC (@FrasesDe3MSC_) / Twitter",
        hashtags: {
            uno: "#Frases",
            dos: "#Fb",
            tres: "#3MSC",
            cuatro: "#ig",
        },
        comentarios: "Ver los 5100 comentarios",
        fecha: "11 DE ABRIL",
        id: 10,
    },
    {
        imagen: "../../src/img/user13.jpg",
        usuario: "Nicolas",
        post: "https://i.pinimg.com/474x/84/00/5a/84005a26c5ddd149d10a7fd012efc797.jpg",
        visualizaciones: "2.102 vistas",
        texto: "Algundiaserefeliz #3msc #tgdt #mariocasas | Frases de peliculas 3msc, Frases de 3msc, Mario casas peliculas",
        hashtags: {
            uno: "#Algundiaserefeliz",
            dos: "#Fb",
            tres: "#3msc",
            cuatro: "#ig",
        },
        comentarios: "Ver los 2600 comentarios",
        fecha: "28 DE OCTUBRE",
        id: 11,
    },
    {
        imagen: "../../src/img/user12.jpg",
        usuario: "After",
        post: "https://t2.fr.ltmcdn.com/es/posts/8/2/8/no_se_de_que_estan_hechas_las_almas_pero_la_mia_y_la_suya_son_una_sola_828_4_600.jpg",
        visualizaciones: "6.652 vistas",
        texto: "Las mejores frases del libro de AFTER - ¡Bonitas y cortas!",
        hashtags: {
            uno: "#AFTER",
            dos: "#Fb",
            tres: "#libro",
            cuatro: "#ig",
        },
        comentarios: "Ver los 8100 comentarios",
        fecha: "08 DE ABRIL",
        id: 12,
    },
    {
        imagen: "../../src/img/user11.jpg",
        usuario: "Andynzein",
        post: "https://www.youtube.com/embed/69_N6rC1tKI",
        visualizaciones: "16.652 vistas",
        texto: "ANDYNZEIN CONSIGUIÓ SU CUBANITA 🔥😎",
        hashtags: {
            uno: "#CUBANITA",
            dos: "#Fb",
            tres: "#ANDYNZEIN",
            cuatro: "#ig",
        },
        comentarios: "Ver los 12.100 comentarios",
        fecha: "18 DE ENERO",
        id: 13,
    },
    
];
